name: "Manual CI (BrowserStack Only)"

on:
  workflow_dispatch:
    inputs:
      platform_name:
        description: "Mobile platform to test"
        type: choice
        options:
          - Android
          - iOS
        default: "Android"
      app:
        description: "BrowserStack App ID override"
        type: string
        required: true
      spec:
        description: "Spec file to run"
        type: string
        default: ""

concurrency:
  group: manual-ci-browserstack-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/browserstack-reusable.yml
    with:
      platform_name: ${{ inputs.platform_name }}
      app_id: ${{ inputs.app }}
      spec: ${{ inputs.spec }}
    secrets: inherit
