name: Mobile tests (Local Emulator)

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  android-emulator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.0

      - name: Install deps
        run: npm install

      - name: Check spec syntax
        run: node --check tests/specs/visual/home-visual.spec.js

      - name: Cache Appium drivers
        uses: actions/cache@v4
        with:
          path: ~/.appium
          key: appium-${{ runner.os }}

      - name: Install Appium driver
        run: |
          npx appium --version
          npx appium driver install uiautomator2
          npx appium driver list --installed

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Download demo app
        run: |
          curl -L -o app.apk https://github.com/webdriverio/native-demo-app/releases/download/v1.0.8/android.wdio.native.app.v1.0.8.apk

      - name: Run emulator + tests
        uses: reactivecircus/android-emulator-runner@v2
        env:
          RUN_TARGET: local
          APP: ${{ github.workspace }}/app.apk
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          profile: pixel_6
          script: |
            npm run test:local
